tfdemo.ASP/Models/MeteoInfoModel.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace tfdemo.ASP.Models
{
    public class MeteoInfoModel
    {
        [JsonProperty("city_info")]
        public CityInfo CityInfo { get; set; }

        public ForecastInfo forecast_info { get; set; }

        public CurrentCondition current_condition { get; set; }
    }
    public class CityInfo
    {
        public string name { get; set; }
        public string country { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string elevation { get; set; }
        public string sunrise { get; set; }
        public string sunset { get; set; }
    }

    public class ForecastInfo
    {
        public object latitude { get; set; }
        public object longitude { get; set; }
        public string elevation { get; set; }
    }

    public class CurrentCondition
    {
        public string date { get; set; }
        public string hour { get; set; }
        public int tmp { get; set; }
        public int wnd_spd { get; set; }
        public int wnd_gust { get; set; }
        public string wnd_dir { get; set; }
        public double pressure { get; set; }
        public int humidity { get; set; }
        public string condition { get; set; }
        public string condition_key { get; set; }
        public string icon { get; set; }
        public string icon_big { get; set; }
    }
}

tfdemo.ASP/Models/ProductModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace tfdemo.ASP.Models
{
    public class ProductModel
    {
        public int Id { get; set; }

        [Required]
        //[RegularExpression(@"/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,20}$/")]
        public string Nom { get; set; }

        [Required]
        [Range(typeof(decimal), "0", "9999")]
        public decimal Prix { get; set; }

        [MaxLength(1000)]
        public string Description { get; set; }

    }
}

tfdemo.ASP/Components/MeteoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using tfdemo.ASP.Models;

namespace tfdemo.ASP.Components
{
    //[ViewComponent]
    public class MeteoViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage reponse = await client.GetAsync(
                    "https://prevision-meteo.ch/services/json/charleroi");
                if(reponse.IsSuccessStatusCode)
                {
                    string json = await reponse.Content.ReadAsStringAsync();
                    MeteoInfoModel model =
                        JsonConvert.DeserializeObject<MeteoInfoModel>(json);
                    return View(model);
                }
                return View(null);
            }
        }


        //public IActionResult Invoke()
        //{

        //}
    }
}

tfdemo.ASP/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace tfdemo.ASP.Controllers
{
    public class DefaultController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PageAvecDonnee()
        {
            //test
            List<string> model = new List<string>
            {
                "Khun", "Thierry", "Mike"
            };
            return View(model);
        }

        public IActionResult AfficherDate()
        {
            DateTime date = DateTime.Now;
            return View(date);
        }
    }
}

tfdemo.ASP/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using tfdemo.ASP.Models;

namespace tfdemo.ASP.Controllers
{
    public class ProductController : Controller
    {
        private static List<ProductModel> dc
            = new List<ProductModel>
            {
                new ProductModel
                { Id = 1, Nom = "Orval", Prix = 4, Description = "Biere Trappiste" },
                new ProductModel
                { Id = 2, Nom = "Carapills", Prix = 1, Description = "Biere de mauvaise qualité" },
                new ProductModel
                { Id = 3, Nom = "Chimay", Prix = 3, Description = "Biere trappiste" },
            };

        public IActionResult Index()
        {
            return View(dc);
        }

        public IActionResult Details(int id)
        {
            ProductModel model = dc.SingleOrDefault(x => x.Id == id);
            if(model == null)
            {
                return NotFound();
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ProductModel model)
        {
            //validation du model
            //si le model est valide
            if (ModelState.IsValid)
            {
                //insertion dans la db
                int maxId = dc.Max(x => x.Id);
                model.Id = maxId + 1;
                dc.Add(model);
                //afficher un message
                //rediriger autre part
                return RedirectToAction("Index");
            }
            // else
            //ajouter les erreurs
            return View(model);
        }
    }
}

tfdemo.ASP/Views/Default/AfficherDate.cshtml
@model DateTime
@{
    ViewData["Title"] = "Afficher Date";
}

<h1>Date Du jour : @Model.Day / @Model.Month / @Model.Year</h1>

tfdemo.ASP/Views/Default/Index.cshtml
@{ 
    int maVariable = 42;
    ViewData["Title"] = "Page Index";
}
<p>Hello World !!!</p>
<p>Changements @maVariable</p>
<h1>Mon titre</h1>
@if(false)
{
    <p>Test</p>
}

@section Scripts {
    <script>
        //alert();
    </script>
}

tfdemo.ASP/Views/Default/PageAvecDonnee.cshtml
@*MonCommentaire*@
@model List<string>
<!-- commentaire html -->
<p>Nombre de personnes : @Model.Count</p>
<ul>
    @foreach (string s in Model)
    {
        <li>@s</li>
    }
</ul>

tfdemo.ASP/Views/Product/Create.cshtml
@model ProductModel

@{
    ViewData["Title"] = "Create un produit";
}

<form action="/product/create" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <input asp-for="Nom" class="form-control" type="text" />
        <span asp-validation-for="Nom"></span>
    </div>
    <div class="form-group">
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description"></span>
    </div>
    <div class="form-group">
        <input asp-for="Prix" class="form-control" type="text" />
        <span asp-validation-for="Prix"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Sauvegarder"/>
    </div>
</form>

tfdemo.ASP/Views/Product/Details.cshtml
@model ProductModel
@{
    ViewData["Title"] = "Details du produit " + Model.Nom;
}

<h1>Details</h1>
<h4>@Model.Nom</h4>
<p>@Model.Description</p>
<p>@Model.Prix</p>

tfdemo.ASP/Views/Product/Index.cshtml
@model List<ProductModel>
@{
    ViewData["Title"] = "Bieres";
}

<h1>Index</h1>
<table class="table">
    <thead>
        <tr>
            <th>Nom</th>
            <th>Description</th>
            <th>Prix</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (ProductModel item in Model)
        {
            <tr>
                <td>@item.Nom</td>
                <td>@item.Description.</td>
                <td>@item.Prix €</td>
                <td>
                    <a asp-controller="Product" asp-action="Details" 
                       asp-route-id="@item.Id">Loupe</a>
                </td>
            </tr>
        }
    </tbody>
</table>

tfdemo.ASP/Views/Shared/Components/Meteo/Default.cshtml
@model MeteoInfoModel
@if (Model == null)
{
    <p>Impossible de charge ce composant</p>
}
else 
{ 
    <p>Temperature : @Model.current_condition.tmp °C</p>
}

tfdemo.ASP/Views/Shared/PartialViews/_nav.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Default" asp-action="Index">My First ASP APP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Default" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Default" asp-action="PageAvecDonnee">Page Avec Données</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Default" asp-action="AfficherDate">Afficher la date</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

tfdemo.ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tfdemo.ASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        @*<partial name="~/Views/Shared/PartialViews/_nav.cshtml" />*@
        @await Html.PartialAsync("PartialViews/_nav.cshtml")
    </header>
    <div class="container">
        <div>
            @await Component.InvokeAsync("Meteo")
        </div>
        <main role="main" class="pb-3" >
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - tfdemo.ASP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>